#!/system/bin/sh

# Zram/Zswap script for android by supersonicninja@xda
# This script is free to use,modify,distribute without any attributions.

# Set 1024MB Swapsize.
echo 1073741824  > /sys/block/zram0/disksize
# Make actual swap file.
/system/bin/tiny_mkswap /dev/block/zram0
# Mount the swap file.
/system/bin/tiny_swapon /dev/block/zram0
# Tell the kernel to use swap.
echo 100 > /proc/sys/vm/swappiness

# This script will compress your ram to gain more ram space (zram).
# Then it will set the extra space to swap file (zswap).
# Unused process are automatically thrown into swap.
# This will help you free the main ram to improve performance.
# Type "free -h" in terminal to check swap usage.
# Delete this file and reboot to simply disable swap.

# Maximum zram swap size of linux is half of the real ram.
# Anything greater will cause errors/slowdouns.
